# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7sDNsp9K31AS_GQbywsFyExF2FTUekL
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0,6,9,8,7,5,3,9,10])
y = np.array([0,8,10,6,4,3,9,8,11])

plt.plot(x, y)
plt.show()